### PR TITLE
Fixes Image Preview on slideshow module.

### PR DESCRIPTION
**Pull request by slip13420**
Fixes silexlabs/Silex#1137

### CODE REVIEW

**Comment by lexoyo** [comment]
This is great @slip13420 
It works fine
Thx

**Comment by lexoyo** [comment]
this is now live on https://preprod.silex.me
@slip13420

**Comment by slip13420** [comment]
Glad to help!

**Comment by lexoyo** [comment]
If you want more there is more ;))
https://github.com/silexlabs/Silex/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Thx again, bye!

**Pull request merged**
